---
# tasks file for Grafana
 - name: detecting Home directory
   shell: echo $HOME
   register: home_dir

 - name: detecting system distribution
   debug: msg=" OS family detected {{ansible_distribution}}-{{ ansible_distribution_major_version}}"

 - include: RedHat.yaml
   vars:
     grafana_rpm: "{{home_dir.stdout}}/{{grafana_package_destination}}"
   when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

 - include: Ubuntu.yaml
   vars:
     grafana_package: "{{grafana_src}}"
     grafana_package_destination: "{{grafana_dest}}"
     grafana_deb: "{{grafana_deb_name}}"
   when: ansible_distribution == "Ubuntu"

 - name: Enable service grafana
   service:
     name: grafana-server
     enabled: yes
   become: yes

 - name: Start service grafana
   service:
     name: grafana-server
     state: started
   become: yes

 - name: getting  grafana daemon status
   shell: systemctl status grafana-server
   become: yes
   register: grafana_status

 - name: testing service grafana status
   debug:
     var: grafana_status
