---
  - name: "Downloading grafana for {{ansible_distribution}}-{{ ansible_distribution_major_version}}"
    copy:
      src: "{{grafana_package}}"
      dest: "{{home_dir.stdout}}/{{grafana_package_destination}}"
      mode: 0611


  - name: "Installing Grafana package for Ubuntu"
    apt:
     deb:  "{{home_dir.stdout}}/{{grafana_package_destination}}/{{grafana_deb}}"
     state: present
    become: yes
