---
  - name: "Downloading vernemq for {{ansible_distribution}}-{{ ansible_distribution_major_version}}"
    get_url:
      url: https://bintray.com/artifact/download/erlio/vernemq/deb/xenial/vernemq_1.6.1-1_amd64.deb
      dest: "{{ vernemq_deb }}"
      validate_certs: false
