---
# tasks file for java
 - name: detecting Home directory
   shell: echo $HOME
   register: home_dir

 - name: copying JAVA oracle package to remote host
   copy:
        src: "{{java_package}}"
        dest: "{{home_dir.stdout}}/{{path}}"
        mode: 0611


 - name: "creating java folder under {{destination}}"
   file:
       path: "{{destination}}/java"
       state: directory
   become: yes

 - name: Unarchiving java package
   unarchive:
            src: "{{home_dir.stdout}}/{{path}}/{{java_package_name}}"
            dest: "{{destination}}/java"
            copy: no
   become: yes

 - name: Telling the system about the new java installation
   shell: update-alternatives --install "/usr/bin/java" "java" "{{destination}}/java/{{java_version}}/bin/java" 1
   become: yes

 - name: Testing the java installation
   shell: java -version && echo $?
   register: isJavaSucc


 - name: Java installation notification
   debug: msg="java is successfully installed "
   when: isJavaSucc.stdout == "0"

 - name: testing if java is already enabled
   shell: grep JAVA_HOME "{{home_dir.stdout}}/.bashrc"  | wc -l
   register: isJAVA_HOMEThere
   become: yes

 - name: Java installation notification
   debug: msg="{{isJAVA_HOMEThere.stdout}}"

 - name: Adding JAVA_HOME to ~/.bashrc (1/2)
   lineinfile:
           path: "{{home_dir.stdout}}/.bashrc"
           line: "{{item}}"
   with_items:
          - "###########JAVA 8###############"
          - "export JAVA_HOME={{destination}}/java/{{java_version}}"
          - "export PATH=$JAVA_HOME/bin:$PATH"
          - "###############################"
   become: yes
   when: isJAVA_HOMEThere.stdout == "0"
